# Generated by Django 4.2.5 on 2023-09-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person", name="name", field=models.CharField(max_length=100),
        ),
    ]
