# Generated by Django 4.2.5 on 2023-09-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0003_alter_person_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
